[0m18:01:16.844191 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109042480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096f6a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096f6780>]}


============================== 18:01:16.847844 | 33fa8d50-eef2-4870-9f38-387e8aef35f6 ==============================
[0m18:01:16.847844 [info ] [MainThread]: Running with dbt=1.9.6
[0m18:01:16.848171 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/giovanistefani/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init datafinance_edw', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:01:16.858341 [debug] [MainThread]: Starter project path: /Users/giovanistefani/git/datafinance-dbt/datafinance/lib/python3.12/site-packages/dbt/include/starter_project
[0m18:01:16.863199 [info ] [MainThread]: 
Your new dbt project "datafinance_edw" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:01:16.863454 [info ] [MainThread]: Setting up your profile.
[0m18:01:29.370849 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 12.572737, "process_in_blocks": "0", "process_kernel_time": 0.172042, "process_mem_max_rss": "101924864", "process_out_blocks": "0", "process_user_time": 0.853307}
[0m18:01:29.371269 [debug] [MainThread]: Command `dbt init` succeeded at 18:01:29.371193 after 12.57 seconds
[0m18:01:29.371512 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094bd400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1097dc230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109042480>]}
[0m18:01:29.371750 [debug] [MainThread]: Flushing usage events
[0m18:01:30.209675 [debug] [MainThread]: An error was encountered while trying to flush usage events
